Repository yunanwg/brilliant-CV, pull requests merged in 2024-08, with the labels that each got.

#53 fix(cv): delete trailing comma in header name in non-latin
  cv.typ
Labels: size/XS

#50 Function and variable refactor
  README.md
  cv.typ
  docs/docs.typ
  letter.typ
  lib.typ
  metadata.toml.schema.json
  template/cv.typ
  template/letter.typ
  template/metadata.toml
  template/modules_en/certificates.typ
  template/modules_en/education.typ
  template/modules_en/professional.typ
  template/modules_en/projects.typ
  template/modules_en/publications.typ
  template/modules_en/skills.typ
  template/modules_fr/certificates.typ
  template/modules_fr/education.typ
  template/modules_fr/professional.typ
  template/modules_fr/projects.typ
  template/modules_fr/publications.typ
  template/modules_fr/skills.typ
  template/modules_zh/certificates.typ
  template/modules_zh/education.typ
  template/modules_zh/professional.typ
  template/modules_zh/projects.typ
  template/modules_zh/publications.typ
  template/modules_zh/skills.typ
  utils/injection.typ
  utils/lang.typ
  utils/styles.typ
Labels: size/XL

#56 feat(template): add font overwrite functionality
  README.md
  cv.typ
  lib.typ
  metadata.toml.schema.json
  template/cv.typ
  template/letter.typ
  template/metadata.toml
  template/modules_en/certificates.typ
  template/modules_en/education.typ
  template/modules_en/professional.typ
  template/modules_en/projects.typ
  template/modules_en/publications.typ
  template/modules_en/skills.typ
  template/modules_fr/certificates.typ
  template/modules_fr/education.typ
  template/modules_fr/professional.typ
  template/modules_fr/projects.typ
  template/modules_fr/publications.typ
  template/modules_fr/skills.typ
  template/modules_zh/certificates.typ
  template/modules_zh/education.typ
  template/modules_zh/professional.typ
  template/modules_zh/projects.typ
  template/modules_zh/publications.typ
  template/modules_zh/skills.typ
  typst.toml
  utils/styles.typ
Labels: size/L
