Repository yunanwg/brilliant-CV, pull requests merged in 2024-07, with the labels that each got.

#21 fix: compile in all languages without error
  metadata.typ
  modules_en/certificates.typ
  modules_en/education.typ
  modules_en/professional.typ
  modules_en/projects.typ
  modules_en/publications.typ
  modules_en/skills.typ
  modules_fr/certificates.typ
  modules_fr/education.typ
  modules_fr/professional.typ
  modules_fr/projects.typ
  modules_fr/publications.typ
Labels: size/M

#24 github: add documentation deployment workflow
  .github/workflows/deploy-docs.yaml
  README.md
  docs/docs.pdf
Labels: size/M

#27 Replace : with = for homepage in metadata.toml
  template/metadata.toml
Labels: size/XS

#33 fix: various minor updates
  .github/workflows/deploy-docs.yaml
  README.md
Labels: size/S

#35 fix(GitHub): fix compile and deploy documentation action
  .github/workflows/deploy-docs.yaml
  docs/docs.typ
Labels: size/XS

#36 Fix custom accent color
  template/metadata.toml
  utils/styles.typ
Labels: size/XS

#37 feat(github): add compile test workflow
  .github/workflows/compile-test.yaml
Labels: size/M

#34 fix: make custom headerInfo working again
  cv.typ
  template/metadata.toml
Labels: size/M

#39 feat: add TOML schema
  metadata.toml.schema.json
  template/metadata.toml
Labels: size/L

#43 fix!(template): correct profile photo import logic
  cv.typ
  lib.typ
  metadata.toml.schema.json
  template/cv.typ
  template/metadata.toml
Labels: size/S

#44 build: bump import version to v2.0.1
  template/cv.typ
  template/letter.typ
  template/modules_en/certificates.typ
  template/modules_en/education.typ
  template/modules_en/professional.typ
  template/modules_en/projects.typ
  template/modules_en/publications.typ
  template/modules_en/skills.typ
  template/modules_fr/certificates.typ
  template/modules_fr/education.typ
  template/modules_fr/professional.typ
  template/modules_fr/projects.typ
  template/modules_fr/publications.typ
  template/modules_fr/skills.typ
  template/modules_zh/certificates.typ
  template/modules_zh/education.typ
  template/modules_zh/professional.typ
  template/modules_zh/projects.typ
  template/modules_zh/publications.typ
  template/modules_zh/skills.typ
  typst.toml
Labels: size/M
