Repository yunanwg/brilliant-CV, pull requests merged in 2025-09, with the labels that each got.

#111 fix: update fontawesome dependency version
  cv.typ
  utils/styles.typ
Labels: size/XS

#110 Correctly center header when no photo is present
  cv.typ
Labels: size/S

#119 feat(github): add upstream publish automation
  .github/workflows/upstream-publish.yaml
Labels: size/L

#120 build: add justfile to streamline development process
  .gitignore
  justfile
Labels: size/M

#122 fix(cv): enhance publication keyList functionality
  cv.typ
  template/modules_en/publications.typ
Labels: size/S
