Repository yunanwg/brilliant-CV, pull requests merged in 2025-02, with the labels that each got.

#84 feat: italian cv
  cv.typ
  template/metadata.toml
  template/modules_it/certificates.typ
  template/modules_it/education.typ
  template/modules_it/professional.typ
  template/modules_it/projects.typ
  template/modules_it/publications.typ
  template/modules_it/skills.typ
Labels: size/L

#77 Adds `header_info_size` variable to metadata
  cv.typ
  metadata.toml.schema.json
  template/metadata.toml
Labels: size/S

#89 Implement skill levels
  cv.typ
Labels: size/M

#92 Improve metadata schema
  metadata.toml.schema.json
  template/metadata.toml
Labels: size/S
